site_name: Grasshopper User Guide
#theme: material
#theme: cinder
pages:
- Quick Start: 'index.md'
- Getting Setup:
  - Installation: 'installation.md'
  - Configuration: 'configs.md'
- Basic Concepts:
   - Listeners: 'concepts/listeners.md'
   - Plugins: 'concepts/plugins.md'
- Common Scenarios:
  - Making Queries: 'usage/queries.md'
- Advanced:
  - Contribution Guide: 'contribution-guide.md'
