site_name: Grasshopper User Guide
#theme: material
#theme: cinder
pages:
- Quick Start: 'index.md'
- Concepts:
   - Listeners: 'concepts/listeners.md'
   - Plugins: 'concepts/plugins.md'
- Usage:
  - Configuration: 'usage/configs.md'
  - Making Queries: 'usage/queries.md'
- Advanced:
  - Contribution Guide: 'contribution-guide.md'
