site_name: Grasshopper User Guide
#theme: material
#theme: cinder
pages:
- Quick Start: 'index.md'
- Getting Setup:
  - Installation: 'installation.md'
  - Configuration: 'configs.md'
- Basic Concepts:
#  - App authentication: 'concepts/app-auth.md'
#  - The Admin UI: 'concepts/admin-ui.md'
#  - Content / Content Types: 'concepts/content.md'
#  - Managing Assets: 'concepts/assets.md'
   - Listeners: 'concepts/listeners.md'
- Common Scenarios:
  - The User Object: 'usage/user.md'
  - Making Queries: 'usage/queries.md'
- Advanced:
  - Contribution Guide: 'contribution-guide.md'
