site_name: Grasshopper Contribution Guide
#theme: material
#theme: cinder
pages:
- Home: 'index.md'
- Installation: 'installation.md'
- 'Basic Concepts':
  - 'App authentication': 'concepts/app-auth.md'
  - 'The Admin UI': 'concepts/admin-ui.md'
  - 'Content / Content Types': 'concepts/content.md'
  - 'Managing Assets': 'concepts/assets.md'
- 'While Programming':
  - 'The User Object': 'usage/user.md'
  - 'Making Queries': 'usage/queries.md'
