site_name: Grasshopper Contribution Guide
#theme: material
#theme: cinder
pages:
- Home: 'index.md'
- Project Overview: 'project-overview.md'
- Dev Workflow: 
    - Generating Docs: 'generating-docs.md'
    - Updating Admin: 'updating-admin.md'
- User Guide: 'user-guide.md'
