site_name: Grasshopper Contribution Guide
#theme: material
#theme: cinder
pages:
- Home: 'index.md'
- Road Map: 'road-map.md'      
- Project Overview: 'project-overview.md'
- Dev Workflow: 
    - Generating Docs: 'generating-docs.md'
- User Guide: 'user-guide.md'
